commit_message: New translations automatically synced from Crowdin
files:
  - source: /"><img src=x onerror=alert(document.cookie)>.txy
    translation: /%two_letters_code%/q1w2.txy
  - source: /android.xml
    translation: /%language%/%original_file_name%
bundles:
  - 1
