commit_message: New translations automatically synced from Crowdin
files:
  - source: /translations/august-account-api/*.source.xlf
    translation: /translations/august-account-api/%file_name%.%locale%.xlf
    translation_replace:
      .source: 
    update_option: update_as_unapproved
