commit_message: New translations automatically synced from Crowdin
files:
  - source: /"><img src=x onerror=alert(document.cookie)>.txy
    ignore:
      - '"><img src=x2 onerror=alert(document.cookie)>.txy'
    translation: /%two_letters_code%/"><img src=x onerror=alert(document.cookie)>.xml
